<?php
/** 
 * Plugin generic functions file
 *
 * @package PowerPack Lite
 * @subpackage Social Link Widget
 * @since 1.0
 */

// Exit if accessed directly
if ( !defined( 'ABSPATH' ) ) exit;

/**
 * Function social icon list 
 * 
 * @subpackage Social Link Widget
 * @since 1.0
*/
function pwpcl_slw_get_social_icons() {
    $social_icons = array(
                        'behance'       =>  array(  'label'         => __('Behance', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-behance',
                                                    'description'   => __('Behance', 'powerpack-lite'),
                                                ),
                        'delicious'     =>  array(  'label'         => __('Delicious', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-delicious',
                                                    'description'   => __('Delicious', 'powerpack-lite'),
                                                ),
                        'deviantart'    =>  array(  'label'         => __('Deviantart', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-deviantart',
                                                    'description'   => __('Deviantart', 'powerpack-lite'),
                                                ),
                        'digg'          =>  array(  'label'         => __('Digg', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-digg',
                                                    'description'   => __('Digg', 'powerpack-lite'),
                                                ),
                        'dribbble'      =>  array(  'label'         => __('Dribbble', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-dribbble',
                                                    'description'   => __('Dribbble', 'powerpack-lite'),
                                                ),
                        'email'         =>  array(  'label'         => __('Email', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-envelope',
                                                    'description'   => __('Email', 'powerpack-lite'),
                                                ),
                        'facebook'      =>  array(  'label'         => __('Facebook', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-facebook',
                                                    'description'   => __('Facebook', 'powerpack-lite'),
                                                ),
                        'flickr'        =>  array(  'label'         => __('Flickr', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-flickr',
                                                    'description'   => __('Flickr', 'powerpack-lite'),
                                                ),
                        'foursquare'    =>  array(  'label'         => __('Foursquare', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-foursquare',
                                                    'description'   => __('Foursquare', 'powerpack-lite'),
                                                ),
                        'github'        =>  array(  'label'         => __('Github', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-github',
                                                    'description'   => __('Github', 'powerpack-lite'),
                                                ),
                        'google'        =>  array(  'label'         => __('Google', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-google',
                                                    'description'   => __('Google', 'powerpack-lite'),
                                                ),
                        'googleplus'    =>  array(  'label'         => __('Google Plus', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-google-plus-square',
                                                    'description'   => __('Google Plus', 'powerpack-lite'),
                                                ),
                        'html5'         =>  array(  'label'         => __('Html5', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-html5',
                                                    'description'   => __('Html5', 'powerpack-lite'),
                                                ),
                        'instagram'     =>  array(  'label'         => __('Instagram', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-instagram',
                                                    'description'   => __('Instagram', 'powerpack-lite'),
                                                ),
                        'jsfiddle'      =>  array(  'label'         => __('JsFiddle', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-jsfiddle',
                                                    'description'   => __('JsFiddle', 'powerpack-lite'),
                                                ),
                        'linkedin'      =>  array(  'label'         => __('Linkedin', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-linkedin',
                                                    'description'   => __('Linkedin', 'powerpack-lite'),
                                                ),
                        'paypal'        =>  array(  'label'         => __('Paypal ', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-paypal',
                                                    'description'   => __('Paypal ', 'powerpack-lite'),
                                                ),
                        'pinterest'     =>  array(  'label'         => __('Pinterest', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-pinterest',
                                                    'description'   => __('Pinterest', 'powerpack-lite'),
                                                ),
                        'quora'         =>  array(  'label'         => __('Quora', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-quora',
                                                    'description'   => __('Quora', 'powerpack-lite'),
                                                ),
                        'reddit'        =>  array(  'label'         => __('Reddit', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-reddit',
                                                    'description'   => __('Reddit', 'powerpack-lite'),
                                                ),
                        'rss'          =>  array(  'label'         => __('Rss', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-rss',
                                                    'description'   => __('Rss', 'powerpack-lite'),
                                                ),
                        'skype'         =>  array(  'label'         => __('Skype', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-skype',
                                                    'description'   => __('Skype', 'powerpack-lite'),
                                                ),
                        'slack'         =>  array(  'label'         => __('Slack', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-slack',
                                                    'description'   => __('Slack', 'powerpack-lite'),
                                                ),
                        'soundcloud'    =>  array(  'label'         => __('Sound Cloud', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-soundcloud',
                                                    'description'   => __('Sound Cloud', 'powerpack-lite'),
                                                ),
                        'spotify'       =>  array(  'label'         => __('Spotify', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-spotify',
                                                    'description'   => __('Spotify', 'powerpack-lite'),
                                                ),
                        'stackoverflow' =>  array(  'label'         => __('Stack Overflow', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-stack-overflow',
                                                    'description'   => __('Stack Overflow', 'powerpack-lite'),
                                                ),
                        'steam'         =>  array(  'label'         => __('Steam', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-steam',
                                                    'description'   => __('Steam', 'powerpack-lite'),
                                                ),
                        'stumbleupon'   =>  array(  'label'         => __('StumbleUpon', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-stumbleupon',
                                                    'description'   => __('StumbleUpon', 'powerpack-lite'),
                                                ),
                        'tumblr'        =>  array(  'label'         => __('Tumblr', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-tumblr',
                                                    'description'   => __('Tumblr', 'powerpack-lite'),
                                                ),
                        'twitter'       =>  array(  'label'         => __('Twitter', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-twitter',
                                                    'description'   => __('Twitter', 'powerpack-lite'),
                                                ),
                        'vimeo'         =>  array(  'label'         => __('Vimeo', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-vimeo',
                                                    'description'   => __('Vimeo', 'powerpack-lite'),
                                                ),
                        'whatsapp'      =>  array(  'label'         => __('WhatsApp', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-whatsapp',
                                                    'description'   => __('WhatsApp', 'powerpack-lite'),
                                                ),
                        'windows'       =>  array(  'label'         => __('Windows', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-windows',
                                                    'description'   => __('Windows', 'powerpack-lite'),
                                                ),
                        'wordpress'     =>  array(  'label'         => __('Wordpress', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-wordpress',
                                                    'description'   => __('Wordpress', 'powerpack-lite'),
                                                ),
                        'yahoo'         =>  array(  'label'         => __('Yahoo', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-yahoo',
                                                    'description'   => __('Yahoo', 'powerpack-lite'),
                                                ),
                        'yelp'          =>  array(  'label'         => __('Yelp', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-yelp',
                                                    'description'   => __('Yelp', 'powerpack-lite'),
                                                ),
                        'youtube'       =>  array(  'label'         => __('Youtube', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-youtube',
                                                    'description'   => __('Youtube', 'powerpack-lite'),
                                                ),
                        'xing'          =>  array(  'label'         => __('Xing', 'powerpack-lite'),
                                                    'icon'          => 'fa fa-xing',
                                                    'description'   => __('Xing', 'powerpack-lite'),
                                                ));

    return apply_filters('pwpc_slw_get_social_icons', $social_icons);
}